/*
 * @see https://github.com/JetBrains/Grammar-Kit
 */
{
  parserClass="me.alanfoster.camelry.blueprint.language.InjectionParser"
  stubParserClass="GeneratedParserUtilBase"

  implements="me.alanfoster.camelry.blueprint.language.psi.InjectionElement"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Injection"
  psiImplClassSuffix="Impl"
  psiPackage="me.alanfoster.camelry.blueprint.language.psi"
  psiImplPackage="me.alanfoster.camelry.blueprint.language.impl"

  psiImplUtilClass="me.alanfoster.camelry.blueprint.language.psi.InjectionPsiImplUtil"

  elementTypeHolderClass="me.alanfoster.camelry.blueprint.language.InjectionTypes"
  elementTypeClass="me.alanfoster.camelry.blueprint.language.psi.InjectionElementType"
  tokenTypeClass="me.alanfoster.camelry.blueprint.language.psi.InjectionTokenType"
}

// ${foo.bar.baz}

injectionLanguage ::= item_*

private item_ ::= (TEXT | propertyDefinition | CRLF)

propertyDefinition ::= FUNCTION_START PROPERTY_NAME FUNCTION_END {
    mixin="me.alanfoster.camelry.blueprint.language.psi.impl.BlueprintInjectionPropertyDefinitionImpl"
    implements="me.alanfoster.camelry.blueprint.language.psi.BlueprintInjectionPropertyDefinition"
    methods = [getName getNameIdentifier setName getPropertyName getPropertyElement getReferencedProperty]
}